### ISSUE TITLE
Unclear how to activate/deactivate caching on ModelLayers

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1069]
When activating the cache on a ModelLayer through

> cache_policy="read_write"

 The cache does not work.

In fact if looking at the source code of FeatureModelGraph, we can see that the readTileFromCache method is always called in buildTile method (readTileFromCache then checks the "cache_policy" option to continue with the cache or to exit) which seems fine, while the writeTileToCache is only called if the option "node_caching" is activated (then writeTileToCache checks the "cache_policy" option to continue with the cache or to exit).

Then, to resume the read cache policy is set through "cache_policy" option, while the write policy is set through the "node_caching" AND the "cache_policy" option which is misunderstanding.

If I am not mistaken the solution is to call "writeTileToCache" in all cases (like the read case) and to remove the "node_caching" option everywhere in the source code.

**Comment by gwaldron** [comment]
By default, caching for a model layer does not apply to the actual scene graph that gets created; it propagates and applies only to the source data (e.g. feature data read from the network). The "node_caching" option enables caching of the actual scene graph as well. We made this optional for the time being because node caching (especially deserializing nodes from disk) can be quite slow.
