### ISSUE TITLE
Win64 GLCore, osg 3.6-rc3: Picking not work 

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1082]
osgEarth: 37a3540000bf4b62c3c20c76fcf8805dfe7d1f7c
OSG 3.6-rc3: 5c489046266facff65cecf9441638ac60c7e837a

osgearth_pick.exe tests\feature_geom.earth:

![image](https://user-images.githubusercontent.com/804941/38253332-b4d589e2-3756-11e8-865e-da61de2cc63a.png)

**Comment by emminizer** [comment]
We've also seen this problem with the text.  You can mitigate this by commenting out the line `t->getStateSet()->removeAttribute(osg::StateAttribute::PROGRAM)` in `LabelControl` in Controls.cpp.

Note that this is not a good fix because it means no VirtualProgram code will apply to the text.  Instead, OSG's built-in text font shader runs.  There are some ramifications to commenting out this line, so I haven't submitted a PR about it.  But this info might help.

I've seen a bug like the one in the lower-left, but with Image Controls.  I think it might be a different manifestation of the same problem.  I haven't had time to investigate that one.

**Comment by remoe** [comment]
@emminizer, thanks for this hint. The picking issue is solved with eb42887db73d6a41f9e5b2ffa3a9186bb169b313. The label render issue need a new entry.
