### ISSUE TITLE
stroke-image not work with URL referrer

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1183]
stroke-image doesn't resolve with referrer. Wrong URI resolve? (master)

https://github.com/gwaldron/osgearth/blob/master/src/osgEarthFeatures/BuildGeometryFilter.cpp#L319

It works with the following:

imageURI = line->imageURI()->evalURI().full();

But I'm not sure it's correct.

**Comment by jasonbeverage** [comment]
Can you give me an example earth file or at least a stroke-image URL that I could use that duplicates the problem.  I'm not sure what you mean by it doesn't work with a URL referrer, are you loading an earth file from the web?

**Comment by remoe** [comment]
yes, we use a web server with an URL to the image.

**Comment by jasonbeverage** [comment]
Remo,

I think this is fixed in 0262e2144fe8779ac8d07600cf294b05c4b968f8.  I tried against a remote earth file and see what you mean.

It still does an eval with the StringExpression but turns it into a URL, so its a little messy.  We should probably create a feature->evalURI or something that returns an actual URI with a referrer instead at some point.

**Comment by remoe** [comment]
Thanks Jason. I will test that soon.
