### ISSUE TITLE
build on ios and Android

### ISSUE THREAD

**Issue by showzh20** [gwaldron/osgearth#1238]
Could you please update the official document about build on ios?
I cannot compile successfully according to official documents(with Xcode 8,9,10)

**Comment by remoe** [comment]
I think iOS and Android is not "official".

**Comment by XenonofArcticus** [comment]
It is not officially supported and sometimes breaks.

Every time we have to build on iOS or Android it is a new adventure.

If you want to email me, I can maybe make some suggestions.

On Nov 7, 2018 9:28 AM, "Remo E" <notifications@github.com> wrote:

I think iOS and Android is not "official".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gwaldron/osgearth/issues/1238#issuecomment-436543882>,
or mute the thread

**Comment by gwaldron** [comment]
The osgEarth team does not maintain an iOS build environment. So we will have to defer to the community to update the docs.
