### ISSUE TITLE
Is there any reason to force RTTPicker's camera to be square?

### ISSUE THREAD

**Issue by 10110111** [gwaldron/osgearth#1254]
My app uses non-square windows, and has some objects with sizes specified in pixels rather than world-coordinate units. Because `RTTPicker` works only with square camera, this results in wrong picks when window's aspect ratio is too different from `1.0`.
Is there any real reason for `RTTPicker` not to support for separate width and height instead of single `cameraSize`? I'd appreciate if it did support this.

**Comment by gwaldron** [comment]
This would require RTTPicker to re-allocate (or at least use a subportion of) the texture viewport whenever the camera viewport changes. Not a huge deal but will require some work.

Another RTTPicker task on the "someday" list is to read back only the pixels needed for the spiral iterator to query instead of reading back the whole image. Again, will take some work but should improve performance.
