### ISSUE TITLE
simplemodel does not support a profile

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#1323]
It is currently not possible to add a simple model with a profile different from the map as shown in the following example: 
```
<map version="2">
    <image name="readymap_imagery" driver="tms">
        <url>http://readymap.org/readymap/tiles/1.0.0/7/</url>
    </image>
     
    <model name="model" driver="simple">
      <profile srs="epsg:31466"/>
      <url>../data/red_flag.osg.100,100,100.scale</url>
      <location>2560000 5634000 10</location>      
    </model>
    
    <viewpoints>
        <viewpoint name="Zoom to model" lat="40.717" long="-74.018" pitch="-60" range="6000"/>    
    </viewpoints>
</map>
```

In class SimpleModelOptions (https://github.com/gwaldron/osgearth/blob/master/src/osgEarthDrivers/model_simple/SimpleModelOptions#L31) there is a _location class member holding the coordinates of the location, but no member _profile, which would be required to support a profile

**Comment by gwaldron** [comment]
The location property in the simple model driver requires the coordinates to be in the Map's SRS. In your case that would be longitude/latitude/altitude.

This is unlikely to change since this construct (model layer with simple driver) no longer exists in osgEarth 3.x (you can use a model annotation instead).

**Comment by gwaldron** [comment]
Update on this:
The "location" is a true GeoPoint in 3.x, so you can say
`<location srs="epsg:31466" x="2560000" y="5634000" z="10"/>`
