### ISSUE TITLE
2.10-bug: Extruded polygon (with holes) with wrong oriented walls

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1417]
Extruded polygons with hole are not rendered correctly. This could also be the case with 3.0.

```css
                   fill: #ffff00a0;
                   altitude-clamping: terrain-gpu;
                   altitude-resolution: 0.01,
                   extrusion-height: 20m;
                   extrusion-flatten: false;
                   altitude-binding: vertex;
```

![image](https://user-images.githubusercontent.com/804941/71254031-ed4b7c80-2329-11ea-930b-f09980c03a79.png)

**Comment by jasonbeverage** [comment]
Thanks for reporting this Remo.  This is because I removed the calls to rewind in OgrUtils in favor of just calling reverse in order to properly support 3d features.  I pushed a change to the 3.0 branch that goes back to the original rewind logic, but only if the data isn't 3D.

I've removed the calls to reverse for 3D, if we find that they need to be consistently reversed over a wide range of data we'll add it back in.

**Comment by remoe** [comment]
Jason, why you have removed "std::reverse" for 3D?

**Comment by jasonbeverage** [comment]
Hi Remo,

Because I'm not sure if reversing the 3d data verts is actually the correct thing to do.  If we could find some spec on the "correct" orientation coming from OGR in 3D that would be helpful, or if there is an obvious toolchain like FME or QGIS or ArcGIS that is ALWAYS going to produce 3d geometry with orientations that need reversed then I think it's probably best to just force the data producers to provide the correct winding since we can't reliably compute the orientation of the polygon in 3D

**Comment by remoe** [comment]
I've backported this to 2.10. Currently I haven't removed "std::reverse". But the issue is fixed.

**Comment by remoe** [comment]
For completeness: it need https://github.com/gwaldron/osgearth/commit/43e6588eb1d4743f8b7628dbb607d4421196821f as well.
