### ISSUE TITLE
engine_mp crash: possible VAO usage inconsistency?

### ISSUE THREAD

**Issue by manisandro** [gwaldron/osgearth#1430]
I have an OpenSceneGraph build which defines `OSG_GL3_FEATURES=1` and hence `osg::State::_forceVertexArrayObject=true` here [1]. Also, `osg::DisplaySettings::instance()->getVertexBufferHint()` is returning `NO_PREFERENCE`, as per default [2].

Now, setting a breakpoint on `glGenVertexArrays`, I see that `osg::Geometry::createVertexArrayStateImplementation` decides whether to generate VAOs based on `osg::State::useVertexArrayObject`, which in my case returns `true` becuase `_forceVertexArrayObject=true` when evaluating [3].

On the other hand, `setupTextureAttributes` in `engine_mp/TileModelCompiler.cpp` uses [4] 

    if(osg::DisplaySettings::instance()->getVertexBufferHint() == osg::DisplaySettings::VERTEX_ARRAY_OBJECT)

to decide whether to call `osg::Array::setVertexBufferObject`. So in my case, this isn't triggered due to `getVertexBufferHint() = NO_PREFERENCE`.

The result for me on Linux intel/mesa is a crash due to a vbo copy with an invalid pointer, which I reported as [5]. But now I'm not sure whether it is really a mesa bug, or rather a bug in osgEarth, i.e. a possible VAO usage inconsistency? All this given that I don't really have in-depth knowledge of OSG or osgEarth.

[1] https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.6/src/osg/State.cpp#L110
[2] https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.6/src/osg/DisplaySettings.cpp#L250
[3] https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.6/include/osg/State#L793
[4] https://github.com/gwaldron/osgearth/blob/master/src/osgEarthDrivers/engine_mp/TileModelCompiler.cpp#L426
[5] https://gitlab.freedesktop.org/mesa/mesa/issues/2344

**Comment by gwaldron** [comment]
Sandro, thanks for the explanation. 

We stopped maintaining the MP terrain engine some time ago, so I am not completely surprised that there are some VAO-related issues there. 

The combination of CMake flags for OSG can also be tricky -- rarely do I use OSG_GL3_FEATURES without going full-on GLCORE [as documented here](https://gist.github.com/gwaldron/a56b0e77e7fa8587b698717d21f9366d). So that lead to some ideas.

In any case, I would strongly recommend using osgEarth 2.10 or newer -- 3.0 will be released very soon -- which defaults to the newer terrain engine. MP is deprecated moving forward so it's highly unlikely we will dive into fixing stuff like this...sorry.

**Comment by manisandro** [comment]
Thanks for the reply - I'd like to switch to the rex engine, but still have issues getting my tile updating logic to work (see [1]). Anyway, I can work around the issue for now with

    osg::DisplaySettings::instance()->setVertexBufferHint( osg::DisplaySettings::VERTEX_ARRAY_OBJECT );

and next development cycle I'll look again into the rex engine.

Closing.

[1] http://forum.osgearth.org/Rex-terrain-engine-and-updating-custom-tile-source-images-with-requiresUpdateCall-td7592935.html#a7592937
