### ISSUE TITLE
why osgearth use so much cpu

### ISSUE THREAD

**Issue by hankern** [gwaldron/osgearth#1508]
when i run a very simple earth file,the program will use very high cpu.i find other globe, for example google earth,stk, even load many images and elevations, they have no such problem.

**Comment by remoe** [comment]
One cannot compare virtual globes. Each of them have their strengths and weaknesses. osgEarth have a lot of strengths in flexibility. So please close this issue and post this here: http://forum.osgearth.org

**Comment by hankern** [comment]
i think one posible problem is frequency load image/elevation images from cpu to gpu of every tile.
can you merge the images to one image to avoid the problem.

**Comment by gwaldron** [comment]
@hankern One reason it appears to use a lot of CPU is because the frames are rendering continuously. There is a rendering mode called "run on demand" in which you only render a new frame when the data changes; older (2.x) versions of osgEarth support this (use the --run-on-demand command line option) but the current 3.0 iteration does not yet support it. It requires a continuous frame loop. This may change in the future.

Is this just an observation, or are you having a particular problem?

**Comment by beachwalker** [comment]
Is there a planned progress to support run-on-demand again? Continous rendering is a "no-go" for a virtual desktop infrastructure (when looking at costs).
