### ISSUE TITLE
Is it possible to simulate the earth spin effect?

### ISSUE THREAD

**Issue by qqk2008** [gwaldron/osgearth#1621]
Hi, I want to simulate the earth spin (move the earth, not the camera) effect. I have tried to put osgEarth::MapNode as the child of osg::MatrixTransform, osg::PositionAttitudeTransform and osgManipulator::Dragger, but failed to get the results, and it seems that osgEarth::MapNode cannot be affected by its parent. I wonder is it possible to simulate the earth spin effect using osgEarth and osg? 

Thanks for help!

**Comment by gwaldron** [comment]
The [osgearth_eci example](https://github.com/gwaldron/osgearth/blob/master/src/applications/osgearth_eci/osgearth_eci.cpp) does just this by placing a rotation matrix above the MapNode. Perhaps you can use that code for reference.

**Comment by qqk2008** [comment]
Thank you for your reply, Glenn. I have run the osgearth_eci example, but It is not my desired effect. The earth doesn't rotate itself, and It is just the sun, the moon and the stars rotating around the earth. I faced the same side of the earth when I moved the slider. In my opinion, the earth spin effect should take the form of a ball rotating around its Z-axis. Any more ideas to realize the earth spin effect?

**Comment by gwaldron** [comment]
Take another look. The `MapNode` is under a `J2000ToECEFTransform` matrix transform, which changes when you move the slider to set the date/time. You face the same point of the earth at you move the slider because the EarthManipulator (the camera controller) is updating as well -- it works relative to the earth itself, not to the ECI frame. In other words, the camera is updating along with the date/time as well to maintain its focal point.

If you want the camera to sit relative to the earth's position, but not match its rotation, you will need to use a different camera manipulator.

**Comment by qqk2008** [comment]
I will look into the example again and figure it out. Thank you very much!
