### ISSUE TITLE
3d Tiles Flashing when loading

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#1697]
Load the Cesium Ion 57588 dataset, when you zoom in you'll see missing tiles at least temporarily when you zoom in.  This looks like it might be an issue where the tileset.json content isn't loading the actual b3dm content immediately and doing it asynchronously.  But I'm also seeing network errors once in awhile so it might also be bad tiles.

**Comment by liugaijin** [comment]
"But I'm also seeing network errors once in awhile so it might also be bad tiles.".
I donnot think so. because I meet the same issue when I loaded the local data, 
and I test the cesium ion 57588 using cesium webgis, it looks normal.

I can share my local data to you for repair the issue.
you can download from this link(one drive):
https://1drv.ms/u/s!AhFFUuJtxetukw88TqNQW2TYz9pZ?e=ODaexn
I will close the share after 7 days.
Regards.

**Comment by jasonbeverage** [comment]
Thanks, I was able to get the data downloaded, you can close the share.
