### ISSUE TITLE
skynode ：The calculation of illumination on the earth's surface is incorrect

### ISSUE THREAD

**Issue by GaoboLi** [gwaldron/osgearth#1699]
The terrain elements involved in the lighting calculation do not match the actual LOD elements, resulting in obvious tile contour in the lighting calculation

**Comment by gwaldron** [comment]
Not enough information. Earth file, screenshot, version, platform...?

**Comment by GaoboLi** [comment]
### osgEarth Version:Latest master.Compiled under windows10-x64(This problem exists in oe3.1 and the latest version, but oe3.1 is more serious) .

- Test Demo: All demos
- screenshot is as follows
>@version 3.1
![3 1](https://user-images.githubusercontent.com/31604509/119434164-30ddbd80-bd4a-11eb-9ed5-4c93dcfdf11c.png)

> @Latest master
![skynode_lighting_bug](https://user-images.githubusercontent.com/31604509/119434276-697d9700-bd4a-11eb-9565-6902ed2e70c0.png)

**Comment by gwaldron** [comment]
Cannot reproduce; please post an earth file, command line, and the output of `osgearth_version --caps`. Thanks

**Comment by GaoboLi** [comment]
1. the result of "osgearth_version.exe --caps"

![捕获](https://user-images.githubusercontent.com/31604509/120915249-55844e80-c6d5-11eb-9a73-3fa3bbe0bf25.PNG)
2. test demo at "Tool osgearth_viewer" by add the following code at the beginning.
        ```
if (argc < 2)
	{
		argc = 3;
		argv[1] = "--sky";
		argv[2] = "simple.earth";
	}
```

**Comment by gwaldron** [comment]
Still cannot reproduce. Sorry!
![image](https://user-images.githubusercontent.com/326618/121232608-c7889f00-c85f-11eb-950c-0ce4d8002d6d.png)

**Comment by RhythmOfTension** [comment]
I'm actually having the same issue since 3.1. Even with current master, just `osgearth_viewer --screen 0 --sky`:

![image](https://user-images.githubusercontent.com/80849292/121401915-f6873980-c961-11eb-96bf-cb174966b3f9.png)

And actually, in another environment, it was like this but now it's ok. I don't know what changed, but something affecting this behavior. I'll try to check tommorow in another environment.

**Comment by RhythmOfTension** [comment]
Sorry, previous screen and --caps was on 3.1, here is how it looks on master:
![image](https://user-images.githubusercontent.com/80849292/121404834-06544d00-c965-11eb-9cb9-93a298166172.png)

```
[osgEarth]  [Capabilities] Capabilities: 
[osgEarth]  [Capabilities]   osgEarth Version:  3.1.0 build 111
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      2.4.1
[osgEarth]  [Capabilities]   GEOS Version:      3.6.3
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 4.6.0 NVIDIA 466.27
[osgEarth]  [Capabilities]   GL Core Profile:   no
```

**Comment by RhythmOfTension** [comment]
Some interesting observations on my another environment (probably I will repeat it on master later):
1. If I add some elevation layers to simple.earth, the effect will disappear, but only on the hemisphere on which the layer is located. If I add one more elevation layer on another hemisphere, effect will disappear completely. For layers I used data/terrain/mt_rainier_90.tif and mt_fuji_90.tif
2. If I add ContourMap and image layer on whole globe (world.tif) effect will completely disappear even with 1 elevation layer.

I will check it later with master.

**Comment by RhythmOfTension** [comment]
Update: confirmed on master. Here is results (i will try to show the same pole, so it's more obvious about hemispheres):

- 1 elevation layer (fuji):
```
<map>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_fuji_90m.tif</url>
    </GDALElevation>
</map>
```
![image](https://user-images.githubusercontent.com/80849292/121564223-e46dcf80-ca23-11eb-8cb0-79996a0626e2.png)

- 1 elevation layer (rainier):
```
<map>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_rainier_90m.tif</url>
    </GDALElevation>
</map>
```
![image](https://user-images.githubusercontent.com/80849292/121564506-2e56b580-ca24-11eb-90be-89ca2c188481.png)

- 2 elevation layers on both hemispheres (looks fine):
```
<map>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_rainier_90m.tif</url>
    </GDALElevation>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_fuji_90m.tif</url>
    </GDALElevation>
</map>
```
- 1 elevation layer (doesn't matter fuji or rainier) and ContoutMap + world.tif (looks fine):
```
<map>
    <ContourMap>
    </ContourMap>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_rainier_90m.tif</url>
    </GDALElevation>
</map>
```
![image](https://user-images.githubusercontent.com/80849292/121564642-5ba36380-ca24-11eb-92a6-a9da06b4af70.png)

- 1 elevation layer with ContourMap and without image layer that covers the entire globe:
```
<map>
    <ContourMap>
    </ContourMap>
    <GDALImage name="Boston GeoTIFF">
        <url>../data/boston-inset.tif</url>
    </GDALImage>
    <GDALElevation name="e1">
        <url>../data/terrain/mt_fuji_90m.tif</url>
    </GDALElevation>
</map>
```
![image](https://user-images.githubusercontent.com/80849292/121566543-4af3ed00-ca26-11eb-8483-12339d8100c7.png)

**Comment by RhythmOfTension** [comment]
Looks like i found the issue. I've always build my osg without -DOPENGL_PROFILE=GL3 option., today i tried to build osg (and rebuild osgearth) with it, and my globe is normal right now. 

Is -DOPENGL_PROFILE=GL3 mandatory for osgEarth in general? Maybe building without it can cause some other global issues which I don't know about yet?

**Comment by gwaldron** [comment]
Glad you found the problem!
Technically GL3 is not mandatory, but I would always recommend using GL3 or GLCORE profile in order to have access to modern features. After all, OpenGL 3 is more than 10 years old and the old fixed-function pipeline should be left in the past where it belongs. OpenSceneGraph itself maintains legacy support for the FFP which is why the option even exists.

**Comment by RhythmOfTension** [comment]
I made a test on another environment. My steps was:

- osg 3.6 branch, Debug build without `-DOPENGL_PROFILE=GL3` and osgEarth master (Debug) compiled against this osg;
- `osgearth_viewerd nodata.earth` still shows this weird illumination;
- reconfigure and rebuild osg 3.6 branch with `-DOPENGL_PROFILE=GL3`;
- rebuild osgEarth master;
- `osgearth_viewerd nodata.earth` and illumination problem is gone.

**Comment by GaoboLi** [comment]
thanks for your answer



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月25日(星期六) 凌晨4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gwaldron/osgearth] skynode ：The calculation of illumination on the earth&#39;s surface is incorrect (#1699)





 
I made a test on another environment. My steps was:
  
osg 3.6 branch, Debug build without -DOPENGL_PROFILE=GL3 and osgEarth master (Debug) compiled against this osg;
 
osgearth_viewerd nodata.earth still shows this weird illumination;
 
reconfigure and rebuild osg 3.6 branch with -DOPENGL_PROFILE=GL3;
 
rebuild osgEarth master;
 
osgearth_viewerd nodata.earth and illumination problem is gone.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RhythmOfTension** [comment]
Hey @gwaldron, recently i got a time to dig into this mystery, and i think i found potential root of the problem. 

`osgEarth::createEmptyNormalMapTexture` is used to create 1x1 texture for default tilenode normals (without any elevation, thats why adding actual elevation layer on this tilenode fixes the problem). The problem is default wrap mode for `osg::Texture`. It's `GL_CLAMP`, and it's forced to `GL_CLAMP_TO_EDGE` for GL3 builds (see `Texture::applyTexParameters`). With `GL_CLAMP` on non-GL3 builds there is non intended (i think) behavior for sampling this 1x1 texture, it's blending with default black border (at least on my setups). More likely it should be explicitly set to `CLAMP_TO_EDGE` on texture creation, if constant value from sampling this 1x1 texture is intent?

I don't know why other people can't reproduce this problem for non-GL3 builds, maybe `GL_CLAMP` mode behavior for 1x1 textures is hardware thing, but i saw this problem on all my different setups, probably not many people still uses non-GL3 builds though. I haven't tested it on current master, but i think the problem can still be there.

**Comment by gwaldron** [comment]
Thanks. I pushed this patch, see if that helps. 8d01cf637
