### ISSUE TITLE
Geometry defect

### ISSUE THREAD

**Issue by quentinBdr** [gwaldron/osgearth#1733]
Hello,
I had osgearth 2.8 (compiled w/ OSG 3.4.0), then switched to osgearth 3.0 (compiled w/ OSG 3.6.5).
I now have a visual defect with some FeatureNode holding geometry. As an example in the following image : 

![step1](https://user-images.githubusercontent.com/15386075/123265735-a086ca00-d4fb-11eb-913a-c81e02374d23.PNG)

The geometry is displayed correctly, but as the camera approches, it crops the geometry as follows : 

![step2](https://user-images.githubusercontent.com/15386075/123265864-c3b17980-d4fb-11eb-9852-306617b3318c.PNG)

This behavior never occured in the older version. Do you have any idea of what can cause this ?

I've arleady disabled near/far culling aswell as FeatureNode culling, but has not changed anything. I've also tried raw osg geometry but still has the same result.

Thanks

**Comment by gwaldron** [comment]
This is probably due to the logarithmic depth buffer (LDB) which is enabled by default. The LDB is useful for viewing objects that are close up and far away at the same time. However, it does not like very long triangles that may intersect the near clip plane. 

For osgEarth utilities you can disable it with the `--nologdepth` switch. You can also try using the "high precision" LDB by using the `--depth2` switch.

A solution that will work better with LDB is to more highly tessellate your geometry so you don't have long triangles.

Hope this helps

**Comment by quentinBdr** [comment]
Thanks for the answer ! I've tried different LBD but did not work. I actually found that a call to frame() has been made before LogarithmicDepthBuffer.install(camera). Switching those two calls fixed the problem.

Thanks again
