### ISSUE TITLE
use TECHNIQUE_GPU and TECHNIQUE_DRAPE draw line or Polygon will warning

### ISSUE THREAD

**Issue by lqzer** [gwaldron/osgearth#1777]
my graphics card is AMD 520，use osgEarth 3.0 or osgearth 3.1. 
the consoles will print "Warning: detected OpenGL error 'invalid value' after applying GLMode 0xdel" when I use THECHNIQUE_GPU draw line or Polygon. and I run osgearth_measure in my computer the consoles will print "Warning: detected OpenGL error ‘invalid value' at after RenderBin::draw(..). 
 
I use Qt 5.12 + osgEarth 3.0，use TECHNIQUE_GPU and TECHNIQUE_DRAPE draw geometry, The display scene will turn black。
I use TECHNIQUE_MAP and TECHNIQUE_SCENE is normal.

Thanks in advance for any hints or advices.

**Comment by gwaldron** [comment]
Please post the output of `osgearth_version --caps`

**Comment by lqzer** [comment]
[osgEarth]   [Capabilities] Capabilities:
[osgEarth]   [Capabilities]  osgEarth Version: 3.0.0
[osgEarth]   [Capabilities]  osgVersion:          3.6.4
[osgEarth]   [Capabilities]  GDALVersion:       2.4.2
[osgEarth]   [Capabilities]   GPU Vendor:       ATI Technologies Inc.
[osgEarth]   [Capabilities]   GPU Renderer    Radeon 520
[osgEarth]   [Capabilities]   GL/Driver Version: 4.6.14831 Compatibility Profile Context 21.5.2 27.20.20903.8001
[osgEarth]   [Capabilities]   GL Core Profile:  no

**Comment by gwaldron** [comment]
Sorry, don't know the answer. Do you get the same warnings when you run `osgearth_viewer annotation.earth` ?

**Comment by lqzer** [comment]
yes

**Comment by gwaldron** [comment]
You might want to read this old thread, which addresses an issue with Qt and Draping.
https://forum.osgearth.org/solved-black-screen-with-drape-mode-in-a-QOpenGLWidget-td7592420.html#a7592421

**Comment by lqzer** [comment]
Thanks gwaldron.
According to the  thread，my Qt application is Normal when use TECHNIQUE_DRAPE draw geometry.

**Comment by elbarto1980** [comment]
Hi @lqzer, I recently got the same problem you described above and I think it might be caused by the OpenGL drivers of your graphic card.

I am using Ubuntu 20.04 on a laptop that has both the integrated Intel graphic card and a dedicated NVidia graphic card with NVidia Prime drivers that allow you to choose which card you want to run your application with.
When I use the NVidia card, everything works correctly, but if I use the Intel card and add to scene geometries that use either TECHNIQUE_GPU or TECHNIQUE_DRAPE, the display scene turns black and I get these warnings: "Warning: detected OpenGL error 'invalid framebuffer operation' at after RenderBin::draw(..)".

I hope I have been a help to you
