### ISSUE TITLE
Why does the Win10SDK function __imp_SetThreadDescription not resolve when using VS2015 to edit osgearth3.1?

### ISSUE THREAD

**Issue by mirro187** [gwaldron/osgearth#1800]
Target platform version is 10.0.14393.0 in General  of vs2015 property pages. 
osg3.6.4

1>------ Build started: Project: osgEarth, Configuration: Debug x64 ------
1>  Threading.cpp
1>     Creating library D:/compileShareLIB/osgearth-osgearth-3.1/build/lib/Debug/osgEarthd.lib and object D:/compileShareLIB/osgearth-osgearth-3.1/build/lib/Debug/osgEarthd.exp
1>Threading.obj : error LNK2019: unresolved external symbol __imp_SetThreadDescription referenced in function "void __cdecl osgEarth::Threading::setThreadName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setThreadName@Threading@osgEarth@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>D:\compileShareLIB\osgearth-osgearth-3.1\build\lib\Debug\osgEarthd.dll : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by jasonbeverage** [comment]
Try the master branch of osgEarth or the 3.2 release and see it works, I did some changes to make it so SetThreadDescription was looked up at runtime instead of linked directly to fix this issue.  That being said we haven't tried building on Visual Studio 2015 in a very long time so it's possible you might need to upgrade Visual Studio.
