### ISSUE TITLE
Why oe 3.2 has black dome,but oe2.8 doesn't, what's the difference between oe3.2 and oe2.8

### ISSUE THREAD

**Issue by Robert-Earth** [gwaldron/osgearth#1970]
@gwaldron
![osgearth2 8-imagery](https://user-images.githubusercontent.com/98998017/152629639-fda9f544-1c7a-40ce-919c-4af3bec15490.png)
<img width="448" alt="osgearth3 2-imagery" src="https://user-images.githubusercontent.com/98998017/152629645-e2218732-1b9e-4626-aee6-50eba3538cd9.png">

**Comment by gwaldron** [comment]
You didn't say which dataset this is, but I presume it is a spherical mercator dataset that has no data about ~85 latitude. The second image is the correct one. The old version tried to fill in the missing data by stretching the texture to the pole, but we eventually removed that since it is technically incorrect.

You can achieve a similar effect by setting the color of the underlying blank globe to something closer to the color of the ocean imagery. In your earth file you can say

```xml
<map>
    <options>
        <terrain color="#7f7fff" ...
```
or something similar.

**Comment by Robert-Earth** [comment]
@gwaldron 
Thank you. But, black hole still appear on Earth poles. no matter using spherical mercator or global mercator, or terrain color. Actually it should be different color on earth poles
