### ISSUE TITLE
Adding hoarding between buildings

### ISSUE THREAD

**Issue by vishwanath377** [gwaldron/osgearth#2078]
How can we add hoardings in between buildings.

**Comment by gwaldron** [comment]
What have you tried?

**Comment by vishwanath377** [comment]
I have edited the mapbox sample program provided in tests repository and placed my location coordinates.
Now I need hoardings in between those buildings.

**Comment by jasonbeverage** [comment]
There isn't anything built into osgearth that will do what you are trying to do.   You might be able to add a separate layer specifying the hoarding locations and use the osgearth styling capabilities or a model placement filter to do it.  

If you know exactly where the hoardings will be and you have a model you want to use then you can just place the models in the location use want using regular openscenegraph code rather than trying to do it with osgearth.
