### ISSUE TITLE
Want know how to convert so many image files.

### ISSUE THREAD

**Issue by la1985** [gwaldron/osgearth#2143]
Hello,

I'm using osgEarth v2.10.2.
more detail development envrionment is like that, osg 3.6.4, visual studio 2013 vc12, windows 10 x64.
and H/W spec like this CPU is Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, RAM is 64.0GB, HDD is 120MB/s Read/Write.

My problem is that convert speed of level 13 whole world terrain image so slow.

Terrain image source has jp format and 15m resolution.
And it's size is 542GB.

The other levels convert time is here,
My estimate time and size of converting level 13 is 40 days and 2.8TB.
![image](https://user-images.githubusercontent.com/19533908/191665699-3d46a2be-d81b-421f-84ac-f54b427566ed.png)

For saving the convert time i tried grouping of image files about 100 groups and convert each group.
Certainly it so fast and takes only 5 days maybe it is parallel process benefit.

But result image file of each group has some redundant files.
And it will makes blank tile in osg earth, worried about that.

Do you have any idea for these parallel processing?
or do you know when convert process was stopped from software error or computer power off or windows auto updating then how it can be contitued convert process from last working file?

This is my convert command with threads, using threads is little fast than no threads option.
> osgearth_conv --in driver gdal --in url image.vrt --out driver tms --out url image.xml --out format jpg  --threads 16

Thank you!

**Comment by gwaldron** [comment]
`osgearth_conv` has an `--extents` option; you could try using that to generate different portions on different machines and then combine the results afterwards.

There is also a `--no-overwrite` option that will skip any tiles already processed; that is helpful if you need to stop the conversion for some reason (like if the machine goes down).

The `--threads` option does help but I have found that going over 4 threads does not really increase the speed much, perhaps because the operation becomes I/O bound.

**Comment by korela1985** [comment]
Thank you for comment.

--extents options will be my best solution.

I'm measuring convert time of using --no-overwrite option or not.

This option save the time of convert with redundant files? or just simple prevent of overwrite?
