### ISSUE TITLE
Actions during update event

### ISSUE THREAD

**Issue by Thomas-Lerman** [gwaldron/osgearth#2225]
I am looking for a memory leak that causes a 32-bit application to run out of memory after a couple of days or so. I have seemed to track it down to some drawing objects that we add, remove, or update. It seems that the reference count prevents some things from being released. I am curious what SHOULD be done during the update event. We currently mostly do the following (are they all needed, any that are not, or any that I did not list that we should if not too many to list):

1. osg::Group::addChild()
2. osg::Group::removeChild()
3. osg::Uniform::set()
4. osgEarth::Annotation:PositionedAnnotationNode::setPosition()
5. osgEarth::Annotation::ImageOverlay::setBounds()
6. AddEventHandler()
7. RemoveEventHandler()
8. osgEarth::Symbology::Geometry::insert()
9. osg::Node::setNodeMask()
10. osgEarth::Annotation::EllipseNode::setPosition() / setRadiusMajor() / setRadiusMinor() / setRotationAngle
11. osgEarth::Annotation::FeatureNode::setFeature()

**Comment by gwaldron** [comment]
Thomas, you are correct in calling all these methods during update.
However, the reason to do things during update is to avoid making unsafe changes to the scene graph - changes that can invalidate the iterators being used in other passes like cull. Unsafe changes do not usually cause memory leaks - they cause crashes.
I don't have any advice other than to remove things one by one until the problem goes away; that may help you narrow down the culprit. Good luck.

**Comment by emminizer** [comment]
Just wanted to chime in briefly. We (outside group) do run tests on osgEarth fairly regularly. We check for leaks on a monthly basis (give or take) in our own use of osgEarth in another application, and it appears clean.

It sounds like you have a case of unbounded growth, or growth where the bounds are larger than you can deal with based on memory model (approx 2gb). We do check for unbounded growth of terrain loading, but only about every 6 months or so; we're due for another soon. Note we do not have checks specifically for osgEarth::Symbology/Annotation for unbounded growth, just terrain caching.

It sounds like instead of a leak you're looking at some case of unbounded growth. You can probably try to track it down by writing small sample apps that continuous generate, add, then remove the nodes you're suspecting (likely #4, 5, 8, 10, 11) to try to narrow down your issue. HTH.

**Comment by Thomas-Lerman** [comment]
I appreciate what you both have said. We are on an older version of osgEarth. I have been on & off trying to fix this since posting. Most details on what I am seeing: within a Group, we have a Feature node, and we setFeature (in the update event) periodically. A reference pointer's count does not seem to go to zero. If we do the same thing, but the Group's nodeMask makes it invisible, we do not loose the memory (at least not anywhere as fast). The same thing occurs if we do not setFeature. This all makes me wonder if something has changed a while ago to fix somehow.
