### ISSUE TITLE
What's the best practice to changing vertex on the fly?

### ISSUE THREAD

**Issue by x1244** [gwaldron/osgearth#2283]
I have many geometry(millions of triangles or points) changed on the fly, so I tried to use osg::Program shader to transforming vertex from geographic(lon/lat) to world(ECEF). When I add the geode to the root node, got a fragmentary triangle, lost some edge.

![piece](https://github.com/gwaldron/osgearth/assets/63945717/d0c0fe15-5bbf-4713-bfa3-7795d2f53024)

When zoom out, got the prefect triangle.

![zoomout](https://github.com/gwaldron/osgearth/assets/63945717/ec9c6ffd-fa96-45b6-a315-b65753d10033)

The triangle Array is

```cpp
    osg::ref_ptr<osg::Vec3Array> verts = new osg::Vec3Array;
    verts->push_back(osg::Vec3(-80.5, 7.4, 1000.));
    verts->push_back(osg::Vec3(-70.5, 5.2, 2000.));
    verts->push_back(osg::Vec3(-75.8, 9.3, 1000.));
```

Add it to the root node

```cpp
    osg::ref_ptr< osg::Node > earthNode = osgDB::readRefNodeFiles( arguments );
    osg::ref_ptr<osg::Group> root = new osg::Group;
    root->addChild( earthNode );   
    ref_ptr<Node> tri = createModel();
    root->addChild(tri);
    configShader(tri->getOrCreateStateSet(), simple_vert, simple_frag);
    viewer.setSceneData(root);
```

I think this maybe caused by some clip process, or there maybe some incorrect boundingbox.

What can I do with the shader? Or should I use osgEarth::VirtualProgram?

What's the best practice to changing vertex on the fly?

Does adding geode to the root node is correct?

The vertex shader is

```c
const std::string simple_vert(R"(#version 430 
layout (location = 0) in vec3 vPos;
layout (location = 1) in vec4 vColor;
out vec4 color;
uniform mat4 osg_ModelViewProjectionMatrix;
vec3 toECEF(vec3 lbh)
{
    const float _a = 6378137.0;
    const float _e2 = 0.006694380047;
    vec2 lb = radians(lbh.xy);
    float sin_lmd = sin(lb.x);
    float cos_lmd = cos(lb.x);
    float sin_b = sin(lb.y);
    float cos_b = cos(lb.y);
    float N = _a/sqrt(1. - _e2*pow(sin_b, 2.0));
    float h = lbh.z;
    float x = (N + h)*cos_b*cos_lmd;
    float y = (N + h)*cos_b*sin_lmd;
    float z = (N*(1.0 - _e2) + h)*sin_b;
    return vec3(x, y, z);
}
void main()
{
    color = vColor;
    vec3 xyz = toECEF(vPos);
    gl_Position = osg_ModelViewProjectionMatrix*vec4(xyz, 1.0);
}
)");
```

The fragment shader is

```c
const std::string simple_frag(R"(#version 430
in vec4 color;
out vec4 fragData;
void main()
{
    fragData = color;
}
)");
```

The source file

[world.cpp.txt](https://github.com/gwaldron/osgearth/files/11429846/world.cpp.txt)

**Comment by gwaldron** [comment]
It is a bit tough to tell what is happening from the screenshots.

Maybe it's depth buffer precision. You can try installing the `LogarithmicDepthBuffer` to see if this helps. Here is some example usage: https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/ExampleResources.cpp#L763
(By the way, this does use the `VirtualProgram` framework, so you may need to use it as well to get the benefit of the LDB).

It might also be GPU precision. Converting from lat/long to ECEF in a 32-bit shader will cause some truncating of coordinates. The result is usually vertex jittering, but other weird things can happen too.

`VirtualProgram` is osgEarth's shader composition framework. If your geometry is totally independent of the Earth, and you don't care about lighting or other shader-based functionality, you don't need it. Otherwise you can take a look at these examples for how to use it:
https://github.com/gwaldron/osgearth/blob/master/src/applications/osgearth_shadercomp/osgearth_shadercomp.cpp

I hope this is helpful.

**Comment by x1244** [comment]
Thanks a lot.

When I use `LogarithmicDepthBuffer` utility, the triangle are greatly improved.

It also releate to [[Geometry defect · Issue #1733 · gwaldron/osgearth · GitHub](https://github.com/gwaldron/osgearth/issues/1733)](https://github.com/gwaldron/osgearth/issues/1733).

> A solution that will work better with LDB is to more highly tessellate your geometry so you don't have long triangles..

When I split the large triangle into multiple small triangles, I got a good geometry.

```cpp
	osg::ref_ptr<osg::Vec3Array> verts = new osg::Vec3Array;
	verts->push_back(osg::Vec3(-80.5, 7.4, 1000.));
	verts->push_back(osg::Vec3(-81.5, 7.2, 2000.));
	verts->push_back(osg::Vec3(-81.8, 7.8, 1000.));
	verts->push_back(osg::Vec3(-81.4, 8.2, 1000.));
	verts->push_back(osg::Vec3(-80.8, 7.8, 1000.));
	verts->push_back(osg::Vec3(-80.5, 7.5, 1000.));
	
	geom->addPrimitiveSet(new osg::DrawArrays(osg::PrimitiveSet::TRIANGLE_FAN, 0, 6));
```
![tri](https://github.com/gwaldron/osgearth/assets/63945717/812e0122-bce9-4f5c-87cc-eb73c48891b0)

I had checked `osgearth_shadercomp`, it shows me the right way.

Thanks again.
