### ISSUE TITLE
KML model wrong size

### ISSUE THREAD

**Issue by marcoma9023** [gwaldron/osgearth#2362]
Good morning,

I'm working with KML with the aim of importing the KML model of a city into an exact latlon.

In Google Earth everything seems to fit together.

The problem arises when the model is uploaded to Osgearth, below is the code:

```
osgEarth::Drivers::KMLOptions kmlOption;
kmlOption.declutter() = false;
kmlOption.modelScale() = 0.0258;

osg::ref_ptr<osg::Node> kmlNode = osgEarth::Drivers::KML::load(osgEarth::URI(subArr->get(i).toString()), mapNode, kmlOption);
kmlNode->getOrCreateStateSet()->setMode(GL_DEPTH_TEST, true);
kmlNode->getOrCreateStateSet()->setDefine(OE_LIGHTING_DEFINE, osg::StateAttribute::OFF | osg::StateAttribute::PROTECTED);
```

as you can see from the code, I define a KMLOptions....
Here the first question, why if I don't define a modelScale is the size of the model altered compared to the original?

Is there a reference or examples I can follow?

Thanks

**Comment by gwaldron** [comment]
Hi there. Honestly, the KML plugin is very old and hasn't been touched in a long time, so I would not be surprised if there are issues there.
I don't recall any automatic scaling, but who knows. Do you have a KML model you can share?

**Comment by marcoma9023** [comment]
HI,

Thanks for the reply.

Below are the steps I took:
1) Exported shp from QGIS
2) Imported from Sketchup and exported to KMZ
3) Open in GoogleEarth to see the spatial reference
4) Open in OSGEarth.
-------------------

[port1.zip](https://github.com/gwaldron/osgearth/files/13072428/port1.zip)

In the attached zip there is:
- shapefile
- kml  + models opened in GoogleEarth and the relative image.
- same files are opened in OSGEarth (kml  + models) + image in OSGEarth...

It seems as if OSGEarth maps different dimensions or units of measurement....I'm stuck!

Thanks

**Comment by plevy** [comment]
I thought there was a quick way to get your shapefile into Sketchup and confirm this works but the general problem is your KML is in feet and there is no conversion to meters happening.  I think the easiest path is to re-import the shapefile into a Sketchup template that uses meters and not feet.

I also couldn't find any KML option in Sketchup to change the units on export.

Try that and if it doesn't work, let me know how you are doing the shapefile to Sketchup import and I can help with the units.  Otherwise there are some things to do with the KML, but better to sort out the initial units prior to export to KML

**Comment by gwaldron** [comment]
Another option is to scale the object in your KML file.

The underlying problem is that the OSG Collada plugin does not scale the model. Rather it just returns the Units information in a plugin data object and expects the user to do the scaling.

**Comment by plevy** [comment]
Right, your model is in inches so if you change the scale in the doc.kml, you get it right:
<Scale><x>0.0254</x><y>0.0254</y><z>0.0254</z></Scale>

![image](https://github.com/gwaldron/osgearth/assets/7724641/a6fe6f5c-b3f4-4531-b8af-9abdc80c5e19)
