### ISSUE TITLE
The EarthManipulator setViewpoint method is invalid

### ISSUE THREAD

**Issue by wddl** [gwaldron/osgearth#2378]
The function of the EarthManipulator class setViewpoint method becomes invalid after duration_s parameter is set。

When EarthManipulator object add to KeySwitchMatrixManipulator object , the setViewpoint method cannot use duration_s parameters

osgearth version is master

Example code is as follows:
```c++
osgGA::KeySwitchMatrixManipulator* keyPtr = new osgGA::KeySwitchMatrixManipulator();
EarthManipulator* pManip = new osgEarth::Util::EarthManipulator();

pManip->getSettings()->setAutoViewpointDurationEnabled(true);
keyPtr->addMatrixManipulator(0 , "earth" , pManip);

osgGA::AnimationPathManipulator* pAnimationManip0 = createAnimationPathManipulator(path0 , matSanlitun);
keyPtr->addMatrixManipulator(1 , "path" , pAnimationManip0);

keyPtr->selectMatrixManipulator(0);

pManip->setViewpoint(vp , time);  //The method becomes invalid after the 'time' parameter is set
```
How to solve this problem?

**Comment by gwaldron** [comment]
What do you mean, the method becomes invalid? What happens?

**Comment by gwaldron** [comment]
If you will kindly post a .cpp that reproduces the issue, we will take a took. Thank you

**Comment by wddl** [comment]
> If you will kindly post a .cpp that reproduces the issue, we will take a took. Thank you

[osgearth_code.txt](https://github.com/gwaldron/osgearth/files/13343481/osgearth_code.txt)

@gwaldron this is cpp file . Thanks!

**Comment by wddl** [comment]
> If you will kindly post a .cpp that reproduces the issue, we will take a took. Thank you

[osgearth_code.txt](https://github.com/gwaldron/osgearth/files/13343500/osgearth_code.txt)

@gwaldron this is cpp file . Thanks!

**Comment by gwaldron** [comment]
OK. I believe this is a "bug" (or rather an oversight) in OSG.

EarthManipulator's `setViewpoint` method depends on `osgGA::CameraManipulator::updateCamera` being called each frame by the main viewer. This happens automatically in OSG. But unfortunately `KeySwitchMatrixManipulator` does not override `updateCamera` in order to call it on the active manipulator.

You should open an OSG bug report or PR for this.

In the meantime, a workaround will be to install your own update callback to call the method manually, something like this:
```c++
#include <osgEarth/Utils>
...
auto em = new EarthManipulator(arguments);

viewer.getCamera()->addUpdateCallback(new LambdaCallback<>(
        [&](osg::NodeVisitor& nv) {
            em->updateCamera(*viewer.getCamera());
        }));
```
Hope that helps.

**Comment by wddl** [comment]
@gwaldron Thanks to helps very much. I understand
