### ISSUE TITLE
osgearth Whether the 3dtiles data format is supported

### ISSUE THREAD

**Issue by lwh504530121** [gwaldron/osgearth#2379]
Excuse me, does osgEarth support the 3D Tiles data format stored locally on disk? If supported, could you please specify the version that includes this capability?

**Comment by jasonbeverage** [comment]
osgEarth has supported 3D tiles since version 3.0 via it's own
implementation.  Version 3.5 added support for Cesium Native which should
provide much better support for 3d tiles across the board.

You can find instructions on how to build and use the cesium native support
here:  https://docs.osgearth.org/en/latest/cesium_native.html

**Comment by lwh504530121** [comment]
I'm trying to use ThreeDTilesLayer and ThreeDTilesetNode, but I'm encountering some difficulties in loading pnts and b3dm 3D tiles formats. Could you please suggest any examples or demos that I could refer to?

**Comment by lwh504530121** [comment]
Hello, I have successfully loaded the b3dm model, but when I loaded the pnts point cloud, I found that I could not view the model normally. If I opened node->setShowBoundingVolumes(true), I could see the bounding box, but the viewer window would be stuck and the memory would stay at 800m. How should I check it? Thank you very much

**Comment by lwh504530121** [comment]
![Uploading 微信截图_20231114222140.png…]()
