### ISSUE TITLE
[HELP] Update vertexarray through nodevisitor, then can't see mode in some view, and pagelod doesn't work

### ISSUE THREAD

**Issue by YHLpuyu** [gwaldron/osgearth#2548]
I have some osgb that has pagelod, which is oblique model. The osgb model is in a plane, I want add it into osgearth on ground. So I must project the vertexes of geometry from plane to sphere, after model loaded.
I project the coords of geometry into world coordinates, and I can see the root model. But maybe the boundingsphere doesn't update, **the child of model doesn't load**, and the model **dispares** in some view.
![image](https://github.com/gwaldron/osgearth/assets/8923933/d4184480-2033-4c7b-a6e0-2b12e1120916)
![image](https://github.com/gwaldron/osgearth/assets/8923933/194ec73d-71e3-481e-92b3-f4a1836a9fff)

any suggestions, if i change the verties of model, and i can still use pagelod for lods, or there is another method.

**Comment by gwaldron** [comment]
Hello. Yes, it sounds like you have culling problems, and you need to update the bounding spheres in your model as well.
If you change the vertex values, you will need to call `dirtyBound() ` on the geometry node so that OSG can recompute the bounding spheres.

For PagedLOD nodes you might also need to reproject the center point of the LOD (`set/getCenter`) and call `dirtyBound()` on that as well, depending on how the scene graph is set up. Good luck!
