### ISSUE TITLE
AnnotationNode culled on the wrong side of the Earth

### ISSUE THREAD

**Issue by rooi** [gwaldron/osgearth#565]
Hi,

When I run and example with annotation nodes (e.g. osgearth_occlusionculling) the PlaceNode seems to get culled when visible, while it seems to appear on the opposite side of the Earth. I noticed that this does not happen when enabling decluttering (tracks example).

Is this an issue specific to my configuration, or is it a general issue?

I'm using a very recent osgEarth version and osg 3.2.1

Roy

**Comment by nmielcarek** [comment]
I also had this same issue. I fixed it by commenting out the following:
src/osgEarthDrivers/engine_mp/MPTerrainEngineNode.cpp
line 419:
    _terrain->getOrCreateStateSet()->setRenderBinDetails(0, "SORT_FRONT_TO_BACK");

I've noticed some work back and forth on the render bins since this change was made in git (13f55f750b54876b2ff849cef39673c99c6c233e), not sure if they're related or not.

I'm on OSG version 3.1.7, osgEarth latest (2b80844)

Nathan

**Comment by rooi** [comment]
Thanks Nathan,

I just got into working with osgEarth again and the issue seems to be resolved in the latest version

Roy
