### ISSUE TITLE
Stability issues with new GLExtensions refactoring and OSG master.

### ISSUE THREAD

**Issue by haozzzzzzzz** [gwaldron/osgearth#570]
http://forum.osgearth.org/Run-Error-td7586987.html

**Comment by jasonbeverage** [comment]
This is due to an issue with the latest GLExtensions refactoring in the OSG master.  I've seen this crash as well as various other random crashes since that change.  My initial thought is that there needs to be a ref_ptr for the GLExtensions in a few places but the old extension mechanism didn't use a ref_ptr so maybe I'm wrong.

**Comment by jasonbeverage** [comment]
Also note that I don't see the crashes with --SingleThreaded.
