### ISSUE TITLE
Build broken with V8 3.30

### ISSUE THREAD

**Issue by parched** [gwaldron/osgearth#582]
```
In file included from /home/james/builds/osgearth/src/osgearth-osgearth-2.6/src/osgEarthDrivers/script_engine_v8/JavascriptEngineV8.cpp:22:0:
/home/james/builds/osgearth/src/osgearth-osgearth-2.6/src/osgEarthDrivers/script_engine_v8/V8Util: In static member function ‘static v8::Handle<v8::Object> V8Util::WrapObject(v8::Isolate*, T*, v8::Handle<v8::ObjectTemplate>, const V8PropertyMap&)’:
/home/james/builds/osgearth/src/osgearth-osgearth-2.6/src/osgEarthDrivers/script_engine_v8/V8Util:50:19: error: ‘New’ is not a member of ‘v8::String’
       result->Set(v8::String::New(it->first.c_str(), it->first.length()), it->second);
```
plus a bunch more. That one at least should be replaced with NewFromUtf8.

**Comment by jefferey** [comment]
Because V8 is updated frequently, we forked a version that osgEarth is guaranteed to build against. You can find it here: https://github.com/pelicanmapping/v8/releases/tag/osgearth-2.5

Furthermore, osgEarth's V8 support has been deprecated in favor of the Duktape library which is already included in the osgEarth source code. When building osgEarth with CMake, if you leave the V8 fields empty it will default to using Duktape for javascript support. The legacy V8 fields remain just for users who still wish to use V8 in lieu of Duktape (and the Duktape fields are there to allow a user to override the included version of Duktape with a different version).

Hope that helps!

**Comment by parched** [comment]
Hi jefferey,

Thank for info, duktape sounds fine. So what variables do I set to use it, I haven't set any V8 variables.

**Comment by gwaldron** [comment]
Duktape support is built in by default; it will build as long as you do NOT include V8.

**Comment by parched** [comment]
But it doesn't appear to be set as the default. I'm just doing
```
cmake ../osgearth-osgearth-2.6
make
```
and it is trying to use V8.

**Comment by parched** [comment]
I dug a little deeper, in src/osgEarthDrivers/CMakeLists.txt
```IF(V8_FOUND)
  ADD_SUBDIRECTORY(script_engine_v8)
ELSEIF(NOT WITH_EXTERNAL_DUKTAPE OR DUKTAPE_FOUND)
  ADD_SUBDIRECTORY(script_engine_duktape)
ENDIF(V8_FOUND)```

so V8 is the default (if found). I'll submit a patch to fix it with a cmake option. Just trying to think what the best option would be
* USE_V8?
* USE_DUKTAPE?
* Something else?

**Comment by gwaldron** [comment]
USE_V8 defaulting to FALSE would be best ... although we'll probably end up deprecating V8 support anyway.

**Comment by parched** [comment]
Won't fix but a solution is to use Duktape.
