### ISSUE TITLE
Horizon info not installed when using annotation feature node

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#815]
The following trace loops:
     [osgEarth]\* [Horizon] No horizon info installed in callback
with following earth (in annotation section):

```
> <feature name="Label on line constraint">
>             <srs>wgs84</srs>
>             <geometry>
>                 LINESTRING(-130 45, -125 44)
>             </geometry>
>             <style type="text/css">
>                               text-content:           "Constrained label";
>                 text-align:     center_center;
>             </style>
>         </feature>
```

Note that if the geometry is not converted to label (if we change the text symbol by a stroke symbol) the trace disappears.

**Comment by gwaldron** [comment]
OBE - message no longer appears

**Comment by moaz007** [comment]
Hi I am relatively new to using Omnet++ and was trying out a simple simulation project and i am receiving this error too. My simulation runs fine but I wanted to fix this error. I have seen the solution but the problem is I cannot find this annotation section in OsgEarth folder. Can you pinpoint me to where do i need to make this changes? Thankyou in anticipation.

**Comment by gwaldron** [comment]
This message used to appear in the method `HorizonCullCallback::isVisible` in `Horizon.cpp`. 
Good luck.

**Comment by moaz007** [comment]
it is still appearing in my simulation. i am trying to run the Boston map example in Omnet++. I cant locate the horizon.cpp or annotation.

**Comment by gwaldron** [comment]
We don't know anything about Omnet -- I suggest you direct your questions to the Omnet community.
Here's the warning:
https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/Horizon.cpp#L406
